### ISSUE TITLE
site assets in filesystem

### ISSUE THREAD

**Issue by jibblett** [amkirwan/moustache-cms#3]
Looks like deleting an asset collection from admin does not delete the asset collection file cache in the filesystem.  is that intentional?  

Also, when an asset such as a jpg is deleted, the associated files are removed from the filesystem, but not the asset directory.

**Comment by amkirwan** [comment]
this looks like a problem with the Carrierwave remove_asset! method but it should be easy to patch

**Comment by amkirwan** [comment]
[a5578a8](http://github.com/amkirwan/handlebar-cms/commit/a5578a889a9547f65529313708c665a4123b9fd4)  Added after_destroy callback to rm site_asset empty directories.
[1ceea11](http://github.com/amkirwan/handlebar-cms/commit/1ceea11c3272b54a2ebdf411875f2ee65517cce2)  Added after_destroy callback to rm asset_collection from file system
