### ISSUE TITLE
Rake fails when seeding db

### ISSUE THREAD

**Issue by n00b2pr0** [amkirwan/moustache-cms#8]
I cloned the app to start a second instance from scratch.  I had changed the db and seed files and got a rake error.  Reverted to default seed file with only a database change and still rake failed.

**In getting started instructions**
After running rake db:seed

rake aborted!
Access to the collection for CurrentState is not allowed since it is an embedded document, please access a collection from the root document.

After checking the db, a site and layout was created but not a user or page.

**Comment by amkirwan** [comment]
made some major changes recently so I'll check to see what the problem is.

**Comment by amkirwan** [comment]
I just finished some final major updates and the rake db:seed file is now working. If you are still having problems with it let me know. For now I'll close the ticket
